[project]
name = "29092026-dag-tmw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "corneliuslinux772-gif", email = "corneliuslinux772@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
29092026-dag-tmw = "29092026_dag_tmw:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
